samples = 1

[inputs]
data_in_0 = [ [ 21,], [ 13,], [ 12,], [ 13,], [ 24,], [ 14,], [ 12,], [ 6,], [ 24,], [ 18,], [ 13,], [ 4,], [ 11,], [ 29,], [ 8,], [ 6,], [ 7,], [ 31,], [ 10,], [ 22,], [ 25,], [ 25,], [ 2,], [ 14,], [ 10,],]
data_out_0 = [ [ 0,], [ 0,], [ 0,], [ 0,], [ 0,], [ 0,], [ 1,], [ -1,], [ 0,], [ 0,],]

[outputs]
data_out_0 = [ [ 0,], [ 0,], [ 0,], [ 0,], [ 0,], [ 0,], [ 1,], [ -1,], [ 0,], [ 0,],]
